language: java

dist: trusty

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: openjdk8
  - jdk: oraclejdk9
  - jdk: openjdk9
  - jdk: oraclejdk10
  - jdk: openjdk10
  - jdk: oraclejdk11
  - jdk: openjdk11
  - jdk: oraclejdk12
  - jdk: openjdk12
  - jdk: oraclejdk17
  - jdk: openjdk17

  allow_failures:
  - jdk: oraclejdk9
  - jdk: openjdk9
  - jdk: oraclejdk10
  - jdk: openjdk10
  - jdk: oraclejdk12
  - jdk: openjdk12
  - jdk: oraclejdk17
  - jdk: openjdk17

script: mvn clean install

after_success:
  - ./after-success.sh
